### ISSUE TITLE
Marriage policy 

### ISSUE THREAD

**Issue by lsciaron** [annunlord/annunlord.github.io#22]
### Motivation

Marriage policy should be added

### Suggestion

The marriage policy could be added with a hyperlink in the marriage section of the contact us section

**Comment by wsciaroni** [comment]
We can set up a google drive folder to be hyperlinked over. I'll try to remember to look into this with Jan the next time I go up to the church.

**Comment by wsciaroni** [comment]
@lsciaron If you can send me this policy I will upload it to the site.

If the policy changes often we should look into other ways though.
